### ISSUE TITLE
Error in run.py 

### ISSUE THREAD

**Issue by Sandroya** [mxx1219/TENURE#2]
I'm glad you could share the code, but I encountered the following error while running the project according to the steps of readme.md. I'm not sure what the situation is. My environment is Java11, PyTorch1.8.0, and Python 3.8. Is this related to the high version of Python?Could you please help me see what the problem is?  My running log is as follows: 

/home/aaa/anaconda3/envs/TENURE36/bin/python /home/aaa/pycharmProjects/TENURE-main/run.py
**Error** in sitecustomize; set PYTHONVERBOSE for traceback:
AttributeError: partially initialized module 'traceback' has no attribute 'format_stack' (most likely due to a circular import)
Error in sitecustomize; set PYTHONVERBOSE for traceback:
AttributeError: partially initialized module 'traceback' has no attribute 'format_stack' (most likely due to a circular import)
Error in sitecustomize; set PYTHONVERBOSE for traceback:
AttributeError: partially initialized module 'traceback' has no attribute 'format_stack' (most likely due to a circular import)
parse jdk ...
num: 7448
parse project ...
num: 654
num: 63
Error in sitecustomize; set PYTHONVERBOSE for traceback:
**AttributeError**: partially initialized module 'traceback' has no attribute 'format_stack' (most likely due to a circular import)
1
Error in sitecustomize; set PYTHONVERBOSE for traceback:
AttributeError: partially initialized module 'traceback' has no attribute 'format_stack' (most likely due to a circular import)
1
org.jfree.chart.renderer.category
Error in sitecustomize; set PYTHONVERBOSE for traceback:
AttributeError: partially initialized module 'traceback' has no attribute 'format_stack' (most likely due to a circular import)
Traceback (most recent call last):
  File "nmt_predict.py", line 3, in <module>
    import torch
  File "/home/aaa/anaconda3/envs/TENURE36/lib/python3.8/site-packages/torch/__init__.py", line 228, in <module>
    __all__ += [name for name in dir(_C)
**NameError: name '_C' is not defined**
Error in sitecustomize; set PYTHONVERBOSE for traceback:
AttributeError: partially initialized module 'traceback' has no attribute 'format_stack' (most likely due to a circular import)
Traceback (most recent call last):
  File "combine.py", line 23, in <module>
    with open("../nmt_model/joint_inference/d4j_result/d4j_{}/{}/{}/{}.txt".format(d4j_version, fl_setting, bug_version, combine_name), "r") as file:
FileNotFoundError: [Errno 2] No such file or directory: '../nmt_model/joint_inference/d4j_result/d4j_v1/perfect/Chart_1/combine_35.txt'
Error in sitecustomize; set PYTHONVERBOSE for traceback:
AttributeError: partially initialized module 'traceback' has no attribute 'format_stack' (most likely due to a circular import)
Traceback (most recent call last):
  File "prt.py", line 727, in <module>
    with open(pred_path, "r") as file:
**FileNotFoundError: [Errno 2] No such file or directory: '../../parsed_data/d4j_v1/perfect/Chart_1/patch_irs.txt'**

**Comment by Sandroya** [comment]
I found the reason , it must run in the terminal instead of PyCharm.
